### ISSUE TITLE
broken image link in user-agent-switcher.md

### ISSUE THREAD

**Issue by manuel-freire** [partridge-tech/chris-blog#19]
browsed from [the blog](https://chris.partridge.tech/2020/extensions-the-next-generation-of-malware/help-for-users/) to github for [technical details](https://github.com/partridge-tech/chris-blog/blob/master/_content/2020/extensions-the-next-generation-of-malware/user-agent-switcher.md) - tried to click on [broken link to the CNC image](https://github.com/partridge-tech/chris-blog/blob/master/2020/extensions-the-next-generation-of-malware/cnc-logic.png), actual path should have been [this one](https://github.com/partridge-tech/chris-blog/blob/master/_content/2020/extensions-the-next-generation-of-malware/cnc-logic.png)

Thanks for the very interesting article!

**Comment by tweedge** [comment]
Sorry about this - to render the page locally you need to use Jekyll, the markdown files are more of the "source" than the destination article. I didn't have time to finish the article so I linked to the in-progress source instead :)
